// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxFLhCmscfY1piRHL2bs_9qzXMRqZfqM',
    appId: '1:281401742100:web:8ff64dc5d4c53f66fea801',
    messagingSenderId: '281401742100',
    projectId: 'inventara-backend-notification',
    authDomain: 'inventara-backend-notification.firebaseapp.com',
    storageBucket: 'inventara-backend-notification.firebasestorage.app',
    measurementId: 'G-3EJ0Z9XY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfWJXq7x5ZCQJYv5RBn3QgB0qTr2c_Js',
    appId: '1:281401742100:android:617139e94b801ec8fea801',
    messagingSenderId: '281401742100',
    projectId: 'inventara-backend-notification',
    storageBucket: 'inventara-backend-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWSaUuGYPgOl-UWAXZMbOqamT-lut2BcQ',
    appId: '1:281401742100:ios:ab9cb937a2341b09fea801',
    messagingSenderId: '281401742100',
    projectId: 'inventara-backend-notification',
    storageBucket: 'inventara-backend-notification.firebasestorage.app',
    iosBundleId: 'com.example.inventara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWSaUuGYPgOl-UWAXZMbOqamT-lut2BcQ',
    appId: '1:281401742100:ios:ab9cb937a2341b09fea801',
    messagingSenderId: '281401742100',
    projectId: 'inventara-backend-notification',
    storageBucket: 'inventara-backend-notification.firebasestorage.app',
    iosBundleId: 'com.example.inventara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfxFLhCmscfY1piRHL2bs_9qzXMRqZfqM',
    appId: '1:281401742100:web:64b34786347f205ffea801',
    messagingSenderId: '281401742100',
    projectId: 'inventara-backend-notification',
    authDomain: 'inventara-backend-notification.firebaseapp.com',
    storageBucket: 'inventara-backend-notification.firebasestorage.app',
    measurementId: 'G-1XHJBYYYFP',
  );
}
